version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Installing all gem versions via Appraisal
          command: bundle exec appraisal install
      - run: mkdir -p ~/tmp/rspec
      - run:
          name: RSpec tests
          command: |
            bundle exec appraisal rspec --format progress --format RspecJunitFormatter --out ~/tmp/rspec/rspec.xml
            bash <(curl -Ls https://coverage.codacy.com/get.sh)
          when: always
      - store_test_results:
          path: ~/tmp/rspec
