name: Ruby

on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [opened, edited]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Installing all gem versions via Appraisal
        run: bundle exec appraisal install
      - name: Create tmp directory
        run: mkdir -p ~/tmp/rspec
      - name: Run tests
        run: bundle exec appraisal rspec --format progress --format RspecJunitFormatter --out ~/tmp/rspec/rspec.xml
      - name: Push to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
